### ISSUE TITLE
should the module update plugins before running rake tasks?

### ISSUE THREAD

**Issue by cristifalcas** [theforeman/puppet-foreman#331]
In init.pp there is this dependency:

      Class['foreman::database']~>
      Foreman::Plugin <| |>

Shouldn't the package first be installed and after that run db::migrate? I think that at least openscap installs files for db::migrate

**Comment by domcleal** [comment]
I don't remember if there's a specific reason it's that way around.  It might have been our unfamiliarity with how plugins would work in practice at the time, or it might be covering up some bugs in how plugins work (i.e. whether you can take a blank DB, activate plugins and db:migrate from scratch without the plugin breaking it).

That said, it works at the moment because all packages for plugins that contain DB migrations or seeds also call them from their post install sections, so installing the package after should perform any necessary steps.  (This is to ensure plugin upgrades also migrate DBs etc.)

**Comment by mmoll** [comment]
what's the status here?

**Comment by cristifalcas** [comment]
i will close it
