### ISSUE TITLE
Ship report processor as a module

### ISSUE THREAD

**Issue by GregSutcliffe** [theforeman/puppet-foreman#390]
According to https://docs.puppetlabs.com/guides/reporting.html#writing-custom-reports it's now expected for reports to live in /lib/puppet/reports within a module on the master to make it available to the master. This is probably a good thing (no more hunting around in /usr for the correct path).

I guess we need to keep the copy in /files for older puppet versions - should we symlink? I don't know how puppet will treat a symlink here, but keeping two actual copies in sync sounds annoying...

**Comment by domcleal** [comment]
This has been possible for quite a while, it should be fine with 3.x (at least).

**Comment by GregSutcliffe** [comment]
Good to know, I'll try to test and get a PR up.

**Comment by ekohl** [comment]
Given we dropped support for 2.7, it should simplify our module.

**Comment by mmoll** [comment]
For now fixed by theforeman/puppet-puppet#353, I suppose? Maybe it makes sense to open a tracker issue to collect stuff that's fixed but should be revistied...

**Comment by GregSutcliffe** [comment]
@mmoll yeah, that could make sense - this fix works for us, but I do like the idea of having a trivial module that people can add to their environment rather than figuring out the path to the reports dir in the puppet codebase.

Happy to close this if we don't think that's going to happen - but I'll leave it open for now to link in to such a tracker.

**Comment by ekohl** [comment]
I don't mind a tracker, but IMHO we should rename it and decouple it from puppet 4 since it's no longer a blocker.

**Comment by ekohl** [comment]
Rephrased the title

**Comment by jyaworski** [comment]
Has there been any progress on this?

**Comment by ekohl** [comment]
Not that I'm aware of, but I think @GregSutcliffe tested it locally and it worked.

**Comment by GregSutcliffe** [comment]
It does work, it's what I do in my own infra to ensure the report processor is available. @jyaworski is it not working with https://github.com/theforeman/puppet-puppet/pull/353? @mmoll seemed to think that would be enough, so I left this alone for a while...

**Comment by rendhalver** [comment]
So do I need to use the foreman puppet module to get this working?
I also have a module called puppet for managing puppet in my environment so that won't work for me.
I was going to prep a PR for getting this setup as a plugin in this module.
Is that acceptable?

**Comment by ekohl** [comment]
The way we deploy this in our usual setup is through our own [puppet module](https://github.com/theforeman/puppet-puppet/blob/b589490874587e654d28e7a395bdff07e9e83854/manifests/server/config.pp#L278-L296). Since that module has much better knowledge of the various puppet paths we chose not to duplicate the knowledge here. There has been discussion about moving it somewhere else, but we never figured out where exactly.

So for puppet 4 currently the recommended way is passing in the correct paths yourself.

I'll comment on https://github.com/theforeman/puppet-foreman/pull/539 further, but I think you're addressing two issues in one PR: shipping as a plugin and changing paths to puppet 4. We should also handle it as two different changes.

When we are changing it, I'm unsure what the best solution is. We intend to drop Puppet 3 support soon anyway, so we must make a change. That means we could change the defaults to the AIO locations and be done with it.

When shipping as a plugin I'm wondering if we should split it off into its own module entirely. puppet-puppet feels to me like the right module, but we have users like yourself that use another module for managing puppet. puppet-foreman doesn't feel correct either since the foreman server doesn't need it. puppet-foreman_proxy is another candidate since there we actually do the integration with puppet, but that's not required. That leaves a new module.

This is me thinking out loud and I'm wondering what others think about it.

**Comment by rendhalver** [comment]
True. I am addressing two separate issues.
I will open a separate PR's for each issue.

I am using my own puppet module fort managing our puppet servers so using your puppet module won't work for me.

I am of the opinion the report processor for foreman should be in this module because it is specifically for foreman. Having it in a module for managing puppet seems like the wrong place and it forces people to use you other module just to get support for a report processor.

**Comment by ekohl** [comment]
I was thinking of a puppet-puppet_foreman (naming is hard, just a suggestion) module that only has the foreman integration bits for puppet. That means the reporting and node.rb including their tests.

**Comment by rendhalver** [comment]
Why not this module?
It's the accepted module for setting up foreman with puppet so it seems like the most logical place.
It currently manages the report processor anyway so it would just be changing how it's managed.

**Comment by ekohl** [comment]
This module is quite big and splitting off the processor, node and its tests would help reduce that.

**Comment by rendhalver** [comment]
True this module is pretty big.
Splitting out the parts that only manage the puppet integration does sound like a good plan.

**Comment by ekohl** [comment]
I'm closing this. Working on a new way and will see where that takes us.
